language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - pytest
deploy:
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
        tags: true
        branch:
            - master
        user: williamcaesar
        password: ${PYPI_PASSWORD}
